---
language: python
python:
  - '3.6'
script:
  - find ~/ -name 'aasdhajkshd*'
  - cd $HOME/build/aasdhajkshd
  - molecule create
  - molecule converge
  - molecule verify
after_script:
  - molecule destroy
before_install:
  - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - sudo apt update && sudo apt install -y ansible unzip git curl wget
  - git log -1 --format='%H'
  - git config --local gc.auto 0
  - git config --global --add safe.directory '*'
  - mkdir -p $HOME/.ansible $HOME/ansible
  - ls -Alh $HOME/bin/; ls -Alh $HOME/
  - export PATH="${BIN}:$PATH"; echo $PATH
  - echo -e "ansible>=2.4\nmolecule>=2.6\ntestinfra>=1.10\npython-vagrant>=0.5.15\napache-libcloud" > $HOME/ansible/requirements.txt
  - pip install -r $HOME/ansible/requirements.txt
  - git version; ansible --version; molecule --version
notifications:
  email:
    on_success: change
    on_failure: always

