---
language: python
python:
  - '3.8'
install:
  - pip3 install ansible molecule testinfra vagrant python-vagrant apache-libcloud urllib3==1.26.6
script:
  - find ~/ -name 'aasdhajkshd*'
  - cd $HOME/build/aasdhajkshd/mongodb
  - git version; ansible --version; molecule --version
  - set
  - molecule create
  - molecule converge
  - molecule verify
after_script:
  - molecule destroy
before_install:
  - git log -1 --format='%H'
  - git config --local gc.auto 0
  - git config --global --add safe.directory '*'
  - mkdir -p $HOME/.ansible $HOME/ansible
  - ls -Alh $HOME/bin/; ls -Alh $HOME/
  - export PATH="${BIN}:$PATH"; echo $PATH
notifications:
  email:
    on_success: change
    on_failure: always

