---
- name: Add APT key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.4 multiverse
    state: present
- name: Install mongodb package
  apt:
    name: mongodb-org=4.4.24
    state: present
- name: Enable MongoDB
  systemd:
    name: mongod
    enabled: true
- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: "0644"
    force: true
  notify: "Restart database"
